name: helm-deploy
on:
  push:
    tags:
      - 'dev-v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: take a code
      uses: actions/checkout@v4
      
    - name: login in to dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ github.repository }}:${{ github.ref_name }}

    - name: deploy to cluster
      run: |
        git clone https://github.com/kirylzhan-stack/helm-argocdtask
        cd helm-argocdtask
        sed -i "s/image: .*/image: ${{ github.ref_name }}/" values.yaml
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add values.yaml
        git commit -m "Update image tag to ${{ github.ref_name }}"
        git push
 