name: helm-deploy
on:
  push:
    tags:
      - 'dev-v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: take a code
      uses: actions/checkout@v4
      
    - name: login in to dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/app-argocdtask:${{ github.ref_name }}

    - name: deploy to cluster
      env:
        API_TOKEN_GITHUB: ${{ secrets.MY_GITHUB_TOKEN }}
      run: |
        git clone https://x-access-token:${{ env.API_TOKEN_GITHUB }}@github.com/kirylzhan-stack/helm-argocdtask.git
        cd helm-argocdtask/myappchart
        sed -i "s/image: .*/image: ${{ secrets.DOCKER_USERNAME }}/app-argocdtask:${{ github.ref_name }}/" values.yaml
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add values.yaml
        git commit -m "Update image tag to ${{ github.ref_name }}"
        git push
 